// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace BotenArneML.Model
{
    public class ModelInput
    {
        [ColumnName("Action"), LoadColumn(0)]
        public string Action { get; set; }


        [ColumnName("Subtitle"), LoadColumn(1)]
        public string Subtitle { get; set; }


    }
}
